### ISSUE TITLE
Fix issues stated by Peter Gergel in requirements catalog

### ISSUE THREAD

**Issue by OHUSAR** [TIS2016/Analyza-spektroskopickych-dat#5]
Fix these issues with requirements catalog:
#### WORK ON [requierements_catalog branch](https://github.com/TIS2016/Analyza-spektroskopickych-dat/tree/requirements_catalog)

---

Sekcie 1, 2 mozu byt. Sekcii 3 nie velmi nerozumiem, preto by som navrhoval:
- pridat strucny opis vstupnych dat
- matematicke vztahy opisat vzorcom (namiesto SUM pouzit symbol sumy apod.)
- strucne vysvetlit co je premenna p-type

Do casti 3.2 by som pridal vysvetlenie jednotlivych funkcii a nejaky vzorec. Necakam samozrejme kompletne fyzikalne vysvetlenie, no clovek, co bude citat vas katalog poziadaviek, mal by si vediet spravit ako-taku predstavu co sa od projektu vyzaduje. Teraz mi to z toho dokumentu nie je uplne jasne.

P.S. pouzivajte spell-checker :-)

**Comment by OHUSAR** [comment]
## Update from Peter Cermak:

Uploadoval som nejake pripomienky. (pozn. asi do google doc-u)
- pouzite clanok HTPsimple a doplnenie specifikacie, taktiez mozete doplnit literaturu

**Comment by vlade44** [comment]
Napis mu prosim potom nech ma prida na ten drive. Rad by som mal pristup k tym filom :D

**Comment by pe-ge** [comment]
Kratke pripomienky:
1. Prepisat vztahy mat. vzorcom
2. Sekcia 3.3 - Pridat nejaky uvod do tejto casti napr: Existuje niekolko sposobo vyratavania profilov spektralnych ciar ako je vidiet v nasled. tabulke... My sa zameriame na nasledujuce 4 profily:
   
   3.3.1 Dopplerov profil
   Dopplerov profil sa pouziva, ked sa vyzaduje XXX a ma vztah:
   YYY
   
   3.3.2. Lorentzov profil
   ...
   3.3.3. Voigtov profil
   ...
   3.3.4. Hartmann-Tranov profil
   ...

Nemusite sa samozrejme drzat tejto formy, ale malo by to vyzerat takymto stylom.

K jednotlivym profilom by som skusil poziadat zadavatela, nech vam 1-2 vetami strucne zhrnie kazdy profil a to potom hodite do katalogu.
Ked tieto veci spravite, mozeme povazovat katalog za finalny, ktory pojde do master branche.
