### ISSUE TITLE
Commit guide

### ISSUE THREAD

**Issue by OHUSAR** [TIS2016/Analyza-spektroskopickych-dat#6]

**Comment by OHUSAR** [comment]
This is practically reluctant, because merge request creates issue itself. Keeping it open, till the request is not merged - and because there is reference in commit.

Rather see #7

**Comment by filipKov** [comment]
subject line 👍 
i would suggest including more info in this format:
 "+ bla bla " - added feature (eg. new implemented functionality, bug fix, etc." )
  => example: "+ Buffer utility class" , "+ fixed typos", ...
"- bla bla" - removed feature

**Comment by OHUSAR** [comment]
OK, I'll add that to the commit guide and make it our holy grail.
